### ISSUE TITLE
Is this the official lv2 plugin?

### ISSUE THREAD

**Issue by michaelwillis** [sfztools/sfizz-lv2#2]
The readme at https://github.com/sfztools/sfizz seems to indicate that it is both a library and lv2 plugin (among other things), but I tried building it and couldn't find an lv2 plugin in the build artifacts.

This repo (sfizz-lv2) doesn't seem to be as actively developed. I was able to build it, and got this error when I tried to load it in Ardour:

```
error: /home/michael/.lv2/sfizz.lv2/sfizz.ttl:65:1: missing ';' or '.'
lilv_world_load_file(): error: Error loading file `file:///home/michael/.lv2/sfizz.lv2/sfizz.ttl'
```

I added a semicolon at the end of that line, and the lv2 plugin would then load in Ardour, but I was unable to determine a way to load the SFZ file.

**Comment by redtide** [comment]
The lv2 plugin is still in development in the [sfizz develop branch], I suppose this repository will be removed soon.

[sfizz develop branch]: https://github.com/sfztools/sfizz/tree/develop/lv2

**Comment by michaelwillis** [comment]
Oh, thanks! I was just building from the master branch, no wonder I couldn't find the lv2 plugin.
